import { ROLES, type Role } from "@/lib/domain";
import { pageTour, type StepDraft } from "@/lib/onboarding/content/helpers";
import { TOUR_TARGETS as T } from "@/lib/onboarding/targets";
import type { TourDefinition } from "@/lib/onboarding/types";

const ALL_ROLES: readonly Role[] = ROLES;

const DASHBOARD_ROLE_COPY: Readonly<
  Record<Role, { title: string; body: string; responsibility: string }>
> = {
  INITIATOR: {
    title: "Очередь подготовки вопроса",
    body: "Здесь собраны паспорта, где нужно уточнить цель, добавить доказательства, устранить замечание или связать поручение с KPI.",
    responsibility: "Инициатор доводит вопрос до состояния, в котором орган может принять мотивированное решение.",
  },
  DATA_OWNER: {
    title: "Очередь подтверждения данных",
    body: "Очередь выделяет критические показатели, качество которых ещё не подтверждено назначенным владельцем. Без источника, актуальности и владельца число не становится полноценным доказательством.",
    responsibility: "Владелец данных подтверждает качество только тех показателей, за которые он назначен ответственным.",
  },
  RISK_OFFICER: {
    title: "Очередь риск-экспертизы",
    body: "Здесь появляются решения без полного risk profile: исходной оценки, мер контроля, остаточного риска, владельца и триггера пересмотра.",
    responsibility: "Риск-офицер показывает, какой риск организация принимает после применения мер.",
  },
  ANALYST: {
    title: "Очередь аналитической проверки",
    body: "Очередь ведёт к альтернативам, допущениям, критическим расчётам и материалам моделей, которые требуют подготовки или независимой проверки.",
    responsibility: "Аналитик обеспечивает сопоставимость вариантов и воспроизводимость выводов.",
  },
  SECRETARY: {
    title: "Очередь корпоративного маршрута",
    body: "Здесь видны вопросы, для которых нужно проверить компетенцию органа, полноту gate evidence, переход или возврат на доработку.",
    responsibility: "Корпоративный секретарь контролирует маршрут, но не принимает бизнес-решение вместо органа.",
  },
  BOARD_MEMBER: {
    title: "Очередь человеческого решения",
    body: "Очередь выводит решения, где органу необходимо сопоставить доказательства, риск и альтернативы либо вынести вердикт по рекомендации ИИ.",
    responsibility: "Член органа фиксирует выбор и мотивировку; алгоритм не получает это полномочие.",
  },
  ADMIN: {
    title: "Очередь управления контуром",
    body: "Администратор видит операционные сигналы платформы и переходит к правилам, ролям и справочникам, не подменяя ответственных за решения.",
    responsibility: "Администратор поддерживает техническую управляемость и воспроизводимость конфигурации.",
  },
};

function dashboardTour(role: Role): TourDefinition {
  const roleCopy = DASHBOARD_ROLE_COPY[role];
  return pageTour({
    id: `page-dashboard-${role.toLowerCase().replaceAll("_", "-")}`,
    version: 1,
    title: `Управленческий контур · ${roleCopy.title}`,
    description: "Ролевая экскурсия по портфелю, ответственности, жизненному циклу и закрытым воротам.",
    route: "/dashboard",
    routeRef: { routeId: "dashboard" },
    roles: [role],
    estimatedMinutes: 3,
    steps: [
      {
        key: "portfolio",
        target: T.dashboardOverview,
        placement: "bottom",
        title: "Управленческий контур",
        body: "Dashboard показывает не количество документов, а активный портфель управленческих решений и состояние их доказательной базы.",
        responsibility: "Сначала определите, где процесс требует вмешательства именно вашей роли.",
        thesisContext: "Единицей управления является решение с полным цифровым следом, а не отдельный документ.",
      },
      {
        key: "responsibility",
        target: T.dashboardActionQueue,
        placement: "bottom",
        title: roleCopy.title,
        body: roleCopy.body,
        responsibility: roleCopy.responsibility,
      },
      {
        key: "criticality",
        target: T.dashboardCriticality,
        placement: "left",
        title: "Решение уровня A",
        body: "Уровень A обозначает наиболее существенное решение: расширенная доказательная база, сценарии, допущения, риск-профиль и независимая проверка обязательны; автоматическое решение запрещено.",
        responsibility: "Проверьте не только срочность, но и класс контроля A/B/C.",
        thesisContext: "Критичность определяет глубину evidence и допустимую роль аналитики, но не ценность решения сама по себе.",
      },
      {
        key: "focus",
        target: T.dashboardFocus,
        placement: "left",
        title: "Сейчас в фокусе",
        body: "Система поднимает управленческий вопрос повышенного внимания и объясняет, сколько обязательных условий следующего перехода не подтверждено.",
        responsibility: "Откройте фокусное решение, если его препятствие относится к вашим полномочиям.",
      },
      {
        key: "lifecycle",
        target: T.dashboardProcessRail,
        placement: "top",
        title: "Семь стадий жизненного цикла",
        body: "Проблема → Данные → Альтернативы → Риски → Решение → Исполнение → Обратная связь. Поток показывает накопление решений и точки управленческого трения.",
        responsibility: "Смотрите, на каком переходе портфель теряет темп и доказательность.",
        thesisContext: "Жизненный цикл объединяет нормативный, информационный, аналитический и контрольный контуры.",
      },
      {
        key: "gates",
        target: T.dashboardGates,
        placement: "left",
        title: "Закрытые контрольные ворота",
        body: "Decision gate не принимает решение. Он проверяет, достаточно ли минимальных доказательств, чтобы безопасно открыть следующую стадию.",
        responsibility: "Закрытые ворота — сигнал конкретного дефицита evidence и ответственной роли.",
        thesisContext: "Формальная готовность отделена от содержательного человеческого выбора.",
      },
      {
        key: "open-passport",
        target: T.dashboardOpenPassport,
        targetPolicy: "optional-rbac",
        placement: "left",
        title: "Открыть цифровой паспорт",
        body: "Переход ведёт от сводного портфеля к полному досье: данным, альтернативам, рискам, расчётам, человеческому решению и пост-оценке.",
        responsibility: "Откройте паспорт уровня A, чтобы увидеть причину блокировки и владельца следующего действия.",
        advance: "target-click",
      },
    ],
  });
}

export const PAGE_TOURS: readonly TourDefinition[] = [
  pageTour({
    id: "page-login",
    version: 1,
    title: "Добро пожаловать в DecisionPassport",
    description: "Введение в жизненный цикл, Human-in-the-loop и ролевую модель до входа.",
    route: "/login",
    routeRef: { routeId: "login" },
    estimatedMinutes: 2,
    steps: [
      {
        key: "welcome",
        target: T.body,
        placement: "center",
        title: "Добро пожаловать в DecisionPassport",
        body: "Это цифровой контур полного жизненного цикла управленческого решения — от постановки вопроса до оценки фактического результата. Для демонстрации выберите роль: каждая роль видит одну доказательную базу через собственные полномочия.",
        responsibility: "Выберите точку зрения, с которой хотите изучить платформу.",
        thesisContext: "Платформа управляет качеством решения, а не только движением документов.",
      },
      {
        key: "lifecycle",
        target: T.loginLifecycle,
        placement: "right",
        title: "Семь стадий решения",
        body: "Проблема, данные, альтернативы, риски, решение, исполнение и обратная связь образуют единый управляемый цикл. Переход открывается после проверки обязательных требований предыдущего этапа.",
        responsibility: "Используйте эту ось как карту всей платформы.",
      },
      {
        key: "human-loop",
        target: T.loginHumanLoop,
        placement: "right",
        title: "Данные → аналитика → рекомендация → решение человека",
        body: "ИИ и расчёты поддерживают анализ, но не получают полномочие принять юридически и управленчески значимое решение.",
        responsibility: "Различайте аналитический вход и зафиксированный вердикт органа управления.",
        thesisContext: "Human-in-the-loop сохраняет ответственность и объяснимость решения.",
      },
      {
        key: "roles",
        target: T.loginRoleGroups,
        placement: "left",
        title: "Одна база — разные полномочия",
        body: "Подготовка, экспертиза, решение и контроль используют общие факты, но отвечают за разные свойства паспорта.",
        responsibility: "Выберите роль; после входа автоматически откроется её первая инструкция.",
      },
    ],
  }),
  ...ROLES.map(dashboardTour),
  pageTour({
    id: "page-decisions",
    version: 1,
    title: "Реестр управленческих решений",
    description: "Коды, критичность, стадия, ответственный, орган, срок и gate в одном operational registry.",
    route: "/decisions",
    routeRef: { routeId: "decisions" },
    roles: ALL_ROLES,
    steps: [
      {
        key: "registry",
        target: T.decisionsRegistry,
        placement: "top",
        title: "Единый реестр вопросов",
        body: "Каждая строка представляет управленческое решение и его текущее состояние, а не карточку документа или задачу документооборота.",
        responsibility: "Найдите решение по коду и сразу оцените критичность, стадию и препятствие перехода.",
      },
      {
        key: "filters",
        target: T.decisionsFilters,
        placement: "bottom",
        title: "Фильтры управленческого внимания",
        body: "Поиск и фильтры отделяют решения по уровню A/B/C, стадии и статусу, чтобы не смешивать подготовку, экспертизу, исполнение и закрытые вопросы.",
        responsibility: "Сформируйте рабочую выборку своей роли, а не просматривайте весь реестр последовательно.",
      },
      {
        key: "criticality",
        target: T.decisionCriticality,
        targetPolicy: "optional-rbac",
        placement: "right",
        title: "Критичность A/B/C",
        body: "A требует максимального доказательного контура и запрещает автоматическое решение; B допускает рекомендацию с проверкой; C может автоматизироваться только в рамках утверждённых правил.",
        responsibility: "Уровень определяет обязательные доказательства и authority.",
      },
      {
        key: "gate",
        target: T.decisionsGate,
        placement: "left",
        title: "Где движение заблокировано",
        body: "Статус gate показывает, есть ли минимально достаточная доказательная база для следующей стадии. Закрытие — не ошибка UI, а управленческий сигнал.",
        responsibility: "Перейдите в паспорт, чтобы увидеть конкретное недостающее evidence.",
      },
      {
        key: "responsibility",
        target: T.decisionsResponsibility,
        placement: "left",
        title: "Кто должен сделать следующий шаг",
        body: "Владелец действия выводится из дефицита gate, ожидающего человеческого вердикта или текущей стадии.",
        responsibility: "Не путайте инициатора решения с текущим ответственным за доказательство.",
      },
    ],
  }),
  pageTour({
    id: "page-decision-new",
    version: 1,
    title: "Создание цифрового паспорта",
    description: "Постановка управленческого вопроса, класса контроля и компетентного органа.",
    route: "/decisions/new",
    routeRef: { routeId: "decision-new" },
    roles: ["INITIATOR", "ADMIN"],
    steps: [
      {
        key: "question",
        target: T.decisionNewForm,
        placement: "right",
        title: "Сформулируйте управленческий вопрос",
        body: "Название идентифицирует решение, а цель описывает измеримое изменение, ради которого организация запускает полный evidence lifecycle.",
        responsibility: "Не подменяйте цель названием документа или проекта.",
      },
      {
        key: "criticality",
        target: T.decisionNewCriticality,
        placement: "left",
        title: "Назначьте класс контроля",
        body: "A, B или C определяют глубину обязательной доказательной базы, правила gates и допустимый уровень применения ИИ.",
        responsibility: "Выбирайте критичность по масштабу последствий и необратимости решения.",
      },
      {
        key: "body",
        target: T.decisionNewBody,
        placement: "right",
        title: "Определите компетентный орган",
        body: "Паспорт заранее фиксирует, кто имеет полномочие принять финальное решение. Аналитики, риск-функция и администратор не заменяют этот орган.",
        responsibility: "Выберите орган, соответствующий типу и критичности вопроса.",
      },
      {
        key: "create",
        target: T.decisionNewSubmit,
        placement: "top",
        title: "Откройте доказательный контур",
        body: "После создания появится паспорт с девятью блоками и первой проверкой перехода от проблемы к данным.",
        responsibility: "Сохранение создаёт управленческий объект, но ещё не означает готовность решения.",
      },
    ],
  }),
  pageTour({
    id: "page-decision-passport",
    version: 2,
    title: "Цифровой паспорт управленческого решения",
    description: "Главное досье: authority, готовность, семь стадий, девять блоков и decision gate.",
    route: "/decisions/:id",
    routeRef: { routeId: "decision-passport", query: { tab: "passport" } },
    roles: ALL_ROLES,
    estimatedMinutes: 5,
    steps: [
      {
        key: "header",
        target: T.decisionHeader,
        placement: "bottom",
        title: "Decision Control Header",
        body: "Код, предмет, тип, инициатор, срок и орган собраны в одной зоне, чтобы пользователь сразу понял, что решается и кто обладает финальным полномочием.",
        responsibility: "Перед чтением материалов проверьте идентичность вопроса и компетенцию органа.",
      },
      {
        key: "criticality",
        target: T.decisionCriticality,
        placement: "bottom",
        title: "Класс контроля решения",
        body: "Критичность A/B/C определяет обязательные блоки и глубину проверок; это не декоративный приоритет.",
        responsibility: "Для уровня A ищите сценарии, ключевые допущения, риск-профиль и независимую проверку.",
      },
      {
        key: "readiness",
        target: T.decisionReadiness,
        placement: "left",
        title: "Готовность доказательной базы",
        body: "Процент отражает полноту обязательных блоков паспорта, а не процент исполнения проекта или вероятность одобрения.",
        responsibility: "Используйте показатель как навигацию к пробелам, а не как оценку качества решения человеком.",
      },
      {
        key: "stages",
        target: T.decisionStageRail,
        placement: "top",
        title: "Семь стадий — позвоночник решения",
        body: "Каждая стадия меняет тип требуемого evidence: от постановки проблемы до факта, отклонения и организационного урока.",
        responsibility: "Текущая стадия показывает, какой вопрос должен быть закрыт следующим.",
        thesisContext: "Gate расположен между стадиями и не смешивается с человеческим вердиктом.",
      },
      {
        key: "evidence-index",
        target: T.evidenceIndex,
        placement: "right",
        title: "Девять блоков доказательной базы",
        body: "Идентификация, данные, альтернативы, экономика, безопасность, риски, решение, исполнение и пост-оценка образуют цифровое досье.",
        responsibility: "Выберите блок с неполной готовностью, чтобы перейти прямо к его материалам.",
      },
      {
        key: "gate",
        target: T.decisionGate,
        placement: "top",
        title: "Decision Gate",
        body: "Ворота проверяют минимальную полноту evidence перед переходом. Они не утверждают предпочтительность варианта и не принимают решение.",
        responsibility: "Сначала прочитайте, сколько требований подтверждено и какая следующая стадия заблокирована.",
        thesisContext: "Контроль формальной готовности отделён от authority органа управления.",
      },
      {
        key: "missing",
        target: T.gateMissingEvidence,
        targetPolicy: "optional-rbac",
        placement: "left",
        title: "Недостающие доказательства и ответственность",
        body: "Система называет конкретное условие, объясняет пробел и показывает роль, обязанную предоставить evidence.",
        responsibility: "Исправляйте причину блокировки, а не пытайтесь обойти gate.",
      },
      {
        key: "deep-link",
        target: T.gateDeepLink,
        targetPolicy: "optional-rbac",
        placement: "left",
        title: "Перейти к месту исправления",
        body: "Ссылка ведёт непосредственно к данным, сравнению, риску, расчёту или поручению, которого не хватает переходу.",
        responsibility: "Используйте deep link как следующий управленческий шаг.",
      },
      {
        key: "tabs",
        target: T.passportTabs,
        placement: "bottom",
        title: "Рабочие пространства досье",
        body: "Вкладки раскрывают сравнение альтернатив, риск-профиль, экономику, поручения, AI analysis и воспроизводимый аудит. Каждая вкладка имеет собственную инструкцию.",
        responsibility: "Продолжите в пространстве, соответствующем вашему текущему вопросу.",
      },
    ],
  }),
  pageTour({
    id: "page-decision-alternatives",
    version: 1,
    title: "Сравнение альтернатив",
    description: "Status quo, единые критерии, аналитический score и отдельный человеческий выбор.",
    route: "/decisions/:id?tab=alternatives",
    routeRef: { routeId: "decision-passport", query: { tab: "alternatives" } },
    roles: ALL_ROLES,
    steps: [
      {
        key: "summary",
        target: T.alternativesSummary,
        placement: "bottom",
        title: "Сценарный контур решения",
        body: "Качество анализа определяется не количеством вариантов, а содержательным различием и сопоставимостью по одному набору критериев.",
        responsibility: "Проверьте число вариантов, критериев и наличие status quo.",
      },
      {
        key: "status-quo",
        target: T.alternativesStatusQuo,
        placement: "right",
        title: "Почему status quo обязателен",
        body: "Вариант «ничего не менять» создаёт базу сравнения цены действия и бездействия. Без него сценарный анализ существенного решения считается неполным.",
        responsibility: "Убедитесь, что статус-кво описан как реальная альтернатива, а не формальная строка.",
        thesisContext: "Baseline выбора предотвращает скрытую предопределённость предлагаемого проекта.",
      },
      {
        key: "matrix",
        target: T.alternativesMatrix,
        placement: "top",
        title: "Единая матрица критериев",
        body: "Безопасность, регуляторика, экономика, сроки, ресурсы, персонал, киберриск и устойчивость применяются одинаково ко всем вариантам.",
        responsibility: "Пустой критерий или разные шкалы делают сравнение непроверяемым.",
      },
      {
        key: "score",
        target: T.alternativesScore,
        placement: "left",
        title: "Score — аналитический ориентир",
        body: "Сумма баллов помогает увидеть различия, но не превращает арифметического лидера в автоматически выбранный вариант.",
        responsibility: "Интерпретируйте score вместе с риском, ограничениями и целью решения.",
      },
      {
        key: "human-decision",
        target: T.alternativesHumanDecision,
        placement: "top",
        title: "Решение человека",
        body: "Уполномоченное лицо отдельно фиксирует выбранную альтернативу и мотивировку. Это действие закрывает evidence, которого не может создать модель.",
        responsibility: "Для уровня A обоснование должно объяснять отклонение или принятие аналитической рекомендации.",
      },
    ],
  }),
  pageTour({
    id: "page-decision-risks",
    version: 1,
    title: "Risk Decision View",
    description: "Исходный риск, мера контроля, остаточный риск, владелец, триггер и допущения.",
    route: "/decisions/:id?tab=risks",
    routeRef: { routeId: "decision-passport", query: { tab: "risks" } },
    roles: ALL_ROLES,
    steps: [
      {
        key: "summary",
        target: T.riskSummary,
        placement: "bottom",
        title: "Риск как часть выбора",
        body: "Risk profile показывает не абстрактную heatmap, а ожидаемую экспозицию до и после конкретных мер реагирования.",
        responsibility: "Оцените совокупный риск, который организация фактически принимает.",
      },
      {
        key: "initial",
        target: T.riskInitial,
        placement: "right",
        title: "Исходный риск",
        body: "Вероятность и воздействие до мер образуют исходную оценку. Она нужна как база, относительно которой проверяется эффект контроля.",
        responsibility: "Проверьте единицы воздействия и основание вероятности.",
      },
      {
        key: "mitigation",
        target: T.riskMitigation,
        placement: "top",
        title: "Мера контроля",
        body: "Mitigation описывает конкретное действие, которое должно изменить вероятность, воздействие или оба параметра.",
        responsibility: "Не принимайте декларацию намерения за работающую меру.",
      },
      {
        key: "residual",
        target: T.riskResidual,
        placement: "left",
        title: "Остаточный риск",
        body: "После мер риск не исчезает автоматически. Остаточная оценка показывает экспозицию, которую организация осознанно принимает вместе с решением.",
        responsibility: "Сопоставьте остаточный риск с аппетитом и мотивировкой выбора.",
        thesisContext: "Decision quality включает прозрачность принятого риска, а не только ожидаемый эффект.",
      },
      {
        key: "owner-trigger",
        target: T.riskOwnerTrigger,
        placement: "left",
        title: "Владелец и триггер пересмотра",
        body: "Владелец наблюдает риск после решения, а триггер задаёт проверяемое условие, при котором оценка должна быть пересмотрена.",
        responsibility: "Без владельца и триггера риск-профиль не замыкается в контрольный контур.",
      },
      {
        key: "assumptions",
        target: T.assumptionsRegister,
        placement: "top",
        title: "Допущение — не факт и не прогноз",
        body: "Допущение фиксирует управленческое предположение о будущем, уровень уверенности, срок действия и владельца. Позже оно проверяется в пост-оценке.",
        responsibility: "Не смешивайте экспертную предпосылку с измеренным фактом или результатом модели.",
      },
    ],
  }),
  pageTour({
    id: "page-decision-economics",
    version: 1,
    title: "Экономика и критические расчёты",
    description: "Трудоёмкость, risk effect, NPV, исходные параметры, атрибуция и независимая проверка.",
    route: "/decisions/:id?tab=economics",
    routeRef: { routeId: "decision-passport", query: { tab: "economics" } },
    roles: ALL_ROLES,
    steps: [
      {
        key: "inputs",
        target: T.economicsInputs,
        placement: "right",
        title: "Расчёт начинается с исходных параметров",
        body: "Трудоёмкость, вероятность, ущерб, денежные потоки и ставка дисконтирования должны быть введены явно и сохраняются вместе с результатом.",
        responsibility: "Проверьте единицы, период и происхождение каждого входа.",
      },
      {
        key: "missing",
        target: T.economicsMissing,
        targetPolicy: "optional-rbac",
        placement: "top",
        title: "Нет параметров — нет денежного эффекта",
        body: "DecisionPassport не подставляет удобные значения по умолчанию. Пока обязательные входы отсутствуют, система показывает дефицит, а не выдуманный результат.",
        responsibility: "Сначала заполните доказуемые входы, затем интерпретируйте расчёт.",
      },
      {
        key: "result",
        target: T.economicsResult,
        placement: "top",
        title: "Расчётный эффект",
        body: "Результат является сценарием по указанным параметрам. Он не становится подтверждённым эффектом компании только потому, что выражен в деньгах.",
        responsibility: "Отделяйте вычисление от причинной атрибуции и официальной отчётности.",
      },
      {
        key: "attribution",
        target: T.economicsAttribution,
        placement: "left",
        title: "Доля атрибуции",
        body: "Attribution share показывает, какая часть изменения обоснованно связана с цифровым контуром, а не со всеми внешними факторами.",
        responsibility: "Не приписывайте платформе весь наблюдаемый эффект без основания.",
      },
      {
        key: "review",
        target: T.economicsReview,
        placement: "left",
        title: "Независимая проверка",
        body: "Критический расчёт подтверждает специалист, отличный от его автора. Это снижает риск самооценки и является условием gate для существенных решений.",
        responsibility: "Проверяющий фиксирует вывод и комментарий в audit trail.",
      },
    ],
  }),
  pageTour({
    id: "page-decision-assignments",
    version: 1,
    title: "Поручения и измеримый результат",
    description: "Decision → Assignment → KPI → Actual result.",
    route: "/decisions/:id?tab=assignments",
    routeRef: { routeId: "decision-passport", query: { tab: "assignments" } },
    roles: ALL_ROLES,
    steps: [
      {
        key: "flow",
        target: T.assignmentsFlow,
        placement: "bottom",
        title: "От решения к результату",
        body: "Поручение переводит принятое решение в ответственность, срок и наблюдаемый показатель результата.",
        responsibility: "Проверьте, что действие действительно реализует выбранное решение.",
      },
      {
        key: "register",
        target: T.assignmentsRegister,
        placement: "top",
        title: "Контур ответственности",
        body: "Реестр связывает формулировку, исполнителя, контрольный срок, KPI и статус исполнения.",
        responsibility: "Просрочка видна как управленческий сигнал, а не только как цвет строки.",
      },
      {
        key: "kpi",
        target: T.assignmentsKpi,
        placement: "left",
        title: "KPI результата обязателен",
        body: "DecisionPassport контролирует не только закрытие задачи, но и достижение измеримого результата. Для уровней A и B поручение без KPI блокирует переход.",
        responsibility: "Свяжите каждое значимое поручение с показателем, который можно проверить после исполнения.",
      },
      {
        key: "actual",
        target: T.assignmentsActual,
        targetPolicy: "optional-rbac",
        placement: "top",
        title: "Исполнение не завершает цикл",
        body: "Статус «исполнено» фиксирует действие. Фактический эффект и отклонение проверяются отдельно в пост-оценке.",
        responsibility: "После выполнения перейдите к Plan → Fact → Lesson.",
      },
    ],
  }),
  pageTour({
    id: "page-decision-ai",
    version: 2,
    title: "AI Analysis Workspace",
    description: "Governance модели, источники, рекомендация, ограничения и обязательный человеческий вердикт.",
    route: "/decisions/:id?tab=ai",
    routeRef: { routeId: "decision-passport", query: { tab: "ai" } },
    roles: ALL_ROLES,
    steps: [
      {
        key: "governance",
        target: T.aiGovernance,
        placement: "bottom",
        title: "Model governance",
        body: "Название, версия, дата валидации и допуск по A/B/C определяют, можно ли использовать модель для этого класса решения.",
        responsibility: "Проверьте governance metadata до чтения вывода модели.",
      },
      {
        key: "sources",
        target: T.aiSources,
        placement: "top",
        title: "Источники анализа",
        body: "Каждая рекомендация должна раскрывать использованные доказательства. Отсутствующий источник является ограничением, а не мелкой технической деталью.",
        responsibility: "Сопоставьте ссылки с данными и альтернативами паспорта.",
      },
      {
        key: "recommendation",
        target: T.aiRecommendation,
        placement: "right",
        title: "Рекомендация и ключевые факторы",
        body: "Модель формирует проверяемый аналитический вход: вывод, обоснование и факторы. Это не команда системе и не автоматически выбранная альтернатива.",
        responsibility: "Оцените согласованность вывода с источниками и целью решения.",
      },
      {
        key: "limitations",
        target: T.aiLimitations,
        placement: "left",
        title: "Неопределённости и ограничения",
        body: "Здесь раскрываются границы модели, ограничения уровня анализа и факты, которые модель не может подтвердить.",
        responsibility: "Учитывайте ограничения в мотивировке человеческого вердикта.",
      },
      {
        key: "not-applied",
        target: T.aiNotApplied,
        placement: "top",
        title: "Рекомендация не применена",
        body: "ИИ предоставляет аналитическую поддержку. До явного вердикта рекомендация не меняет выбранный вариант и не запускает исполнение.",
        responsibility: "Не путайте наличие рекомендации с решением организации.",
        thesisContext: "Human-in-the-loop сохраняет полномочие и ответственность за человеком и органом управления.",
      },
      {
        key: "human-verdict",
        target: T.aiHumanVerdict,
        placement: "top",
        title: "Три равноправных человеческих исхода",
        body: "Принять, принять с изменениями или отклонить — равноправные действия. Для уровня A вердикт и его мотивировка обязательны.",
        responsibility: "Зафиксируйте не только исход, но и причину согласия или несогласия с моделью.",
      },
    ],
  }),
  pageTour({
    id: "page-decision-audit",
    version: 1,
    title: "История конкретного решения",
    description: "Воспроизводимый след участников, переходов, доказательств и вердиктов.",
    route: "/decisions/:id?tab=audit",
    routeRef: { routeId: "decision-passport", query: { tab: "audit" } },
    roles: ALL_ROLES,
    steps: [
      {
        key: "timeline",
        target: T.decisionAuditTimeline,
        placement: "top",
        title: "Хронология решения",
        body: "Timeline показывает человеческим языком, кто, когда и что изменил в этом паспорте — от создания до закрытия.",
        responsibility: "Используйте историю, чтобы восстановить основание перехода или вердикта.",
        thesisContext: "Воспроизводимость превращает решение в проверяемый цифровой след.",
      },
      {
        key: "technical",
        target: T.auditTechnical,
        targetPolicy: "optional-rbac",
        placement: "left",
        title: "Техническая запись по запросу",
        body: "Before/after и служебные коды скрыты внутри раскрываемой детали, чтобы основной интерфейс оставался управленческим, а точность аудита сохранялась.",
        responsibility: "Раскрывайте JSON только когда нужна техническая проверка изменения.",
      },
    ],
  }),
  pageTour({
    id: "page-indicators",
    version: 1,
    title: "Каталог управленческих показателей",
    description: "Единое определение, формула, источник, владелец, актуальность и качество.",
    route: "/indicators",
    routeRef: { routeId: "indicators" },
    roles: ALL_ROLES,
    steps: [
      {
        key: "catalog",
        target: T.indicatorCatalog,
        placement: "top",
        title: "Единая версия показателя",
        body: "Каталог фиксирует бизнес-смысл каждого показателя, чтобы разные органы не принимали решения на несовместимых определениях одного числа.",
        responsibility: "Начинайте проверку не со значения, а с утверждённого определения.",
      },
      {
        key: "definition",
        target: T.indicatorDefinition,
        placement: "left",
        title: "Формула, источник и владелец",
        body: "Число без источника и владельца данных не считается полноценным доказательством для существенного решения.",
        responsibility: "Проверьте формулу, единицу, систему-источник и назначенного владельца.",
      },
      {
        key: "freshness",
        target: T.indicatorFreshness,
        placement: "left",
        title: "Актуальность и допустимый лаг",
        body: "Дата значения сравнивается с политикой актуальности. Просроченное измерение остаётся фактом, но требует обновления перед использованием в gate.",
        responsibility: "Не подтверждайте качество только по наличию значения.",
      },
      {
        key: "criticality",
        target: T.decisionCriticality,
        targetPolicy: "optional-rbac",
        placement: "right",
        title: "Критическое доказательство",
        body: "Критический показатель влияет на обязательность подтверждения качества и может закрыть переход решения к следующей стадии.",
        responsibility: "Приоритизируйте показатели, от которых зависит decision gate.",
      },
    ],
  }),
  pageTour({
    id: "page-indicator-detail",
    version: 1,
    title: "Карточка показателя и data lineage",
    description: "От системы-источника до решения и уполномоченного органа.",
    route: "/indicators/:id",
    routeRef: { routeId: "indicator-detail" },
    roles: ALL_ROLES,
    steps: [
      {
        key: "definition",
        target: T.indicatorDefinition,
        placement: "bottom",
        title: "Data contract показателя",
        body: "Бизнес-смысл, формула, источник, единица, частота и правила качества образуют утверждённый контракт доказательства.",
        responsibility: "Проверьте, что значение интерпретируется одинаково во всех решениях.",
      },
      {
        key: "nature",
        target: T.indicatorNature,
        placement: "left",
        title: "Факт, прогноз и допущение нельзя смешивать",
        body: "Факт измерен системой или подтверждённым документом; прогноз вычислен моделью; допущение принято экспертом о будущем. Их визуальная и методическая природа различается.",
        responsibility: "Всегда называйте природу значения рядом с числом.",
      },
      {
        key: "freshness",
        target: T.indicatorFreshness,
        placement: "left",
        title: "Текущее доказательство",
        body: "Версия, дата и лаг показывают, какое именно значение было доступно в момент подготовки решения.",
        responsibility: "Сопоставьте лаг с утверждённым пределом актуальности.",
      },
      {
        key: "lineage",
        target: T.indicatorLineage,
        placement: "top",
        title: "Восстановимое происхождение значения",
        body: "Data lineage ведёт от source system через интеграцию и контроль качества к определению, версии факта, решению и органу управления.",
        responsibility: "Проверьте статус, дату, владельца и версию каждого узла; demo-маршрут не выдавайте за промышленную интеграцию.",
        thesisContext: "Прослеживаемость связывает информационный контур с юридически значимым решением.",
      },
      {
        key: "history",
        target: T.indicatorHistory,
        placement: "top",
        title: "История версий",
        body: "Датированный ряд позволяет восстановить значение, использованное в конкретный момент, а не подменять его текущим числом.",
        responsibility: "Используйте историю для аудита и последующей проверки допущений.",
      },
    ],
  }),
  pageTour({
    id: "page-kpi",
    version: 1,
    title: "Baseline → Pilot и зрелость процесса",
    description: "Сопоставимые выборки, абсолютный delta, границы причинности и maturity continuum.",
    route: "/kpi",
    routeRef: { routeId: "kpi" },
    roles: ALL_ROLES,
    steps: [
      {
        key: "baseline",
        target: T.kpiBaseline,
        placement: "bottom",
        title: "Baseline и pilot — две выборки",
        body: "Изменение процесса оценивается на одинаково определённых KPI до и после запуска цифрового контура.",
        responsibility: "Не сравнивайте проценты, пока не проверены период и состав выборок.",
      },
      {
        key: "sample",
        target: T.kpiSample,
        placement: "right",
        title: "Размер и период — часть результата",
        body: "n и интервал наблюдения раскрываются вместе со значением. Без них улучшение нельзя интерпретировать как доказательство эффекта.",
        responsibility: "Оцените сопоставимость baseline и pilot до чтения delta.",
        thesisContext: "Методика ограничивает выводы пилотной выборкой и не заявляет причинность автоматически.",
      },
      {
        key: "comparison",
        target: T.kpiComparison,
        placement: "top",
        title: "Абсолютное изменение и направление",
        body: "Каждая пара использует собственную единицу и направление улучшения: меньше дней может быть лучше, а большая доля обоснованных решений — лучше.",
        responsibility: "Читайте абсолютный delta вместе с единицей, а не как маркетинговый процент роста.",
      },
      {
        key: "maturity",
        target: T.maturityScale,
        placement: "top",
        title: "Maturity continuum 1–5",
        body: "Фрагментарный → Регламентированный → Интегрированный → Предиктивный → Адаптивный. Индекс рассчитывается по KPI процесса пилота.",
        responsibility: "Смотрите период, выборку и число учтённых KPI рядом с индексом.",
        thesisContext: "Это авторская пилотная оценка, не официальный показатель АО «НАК «Казатомпром».",
      },
    ],
  }),
  pageTour({
    id: "page-models",
    version: 1,
    title: "Governance моделей ИИ",
    description: "Назначение, версия, владелец, валидация, качество, ограничения и допуск.",
    route: "/models",
    routeRef: { routeId: "models" },
    roles: ALL_ROLES,
    steps: [
      {
        key: "human-loop",
        target: T.modelHumanLoop,
        placement: "bottom",
        title: "ИИ встроен в Human-in-the-loop",
        body: "Путь заканчивается человеческим вердиктом: данные и модель создают аналитический материал, но не получают authority органа управления.",
        responsibility: "Оценивайте модель как участника аналитического контура, а не как автономного решателя.",
      },
      {
        key: "registry",
        target: T.modelRegistry,
        placement: "top",
        title: "Реестр допустимых моделей",
        body: "Каждая модель раскрывает назначение, входы, владельца, версию, дату валидации и измеренные метрики качества.",
        responsibility: "Не используйте модель вне зарегистрированного назначения.",
      },
      {
        key: "governance",
        target: T.modelGovernance,
        placement: "left",
        title: "Ограничения и допуск A/B/C",
        body: "Допуск означает право сформировать аналитическую рекомендацию для указанной критичности, а не право принять решение.",
        responsibility: "Проверьте актуальность валидации и ограничения до запуска анализа.",
      },
    ],
  }),
  pageTour({
    id: "page-lessons",
    version: 1,
    title: "Корпоративная память решений",
    description: "Plan → Fact → Cause → Lesson и повторное использование опыта.",
    route: "/lessons",
    routeRef: { routeId: "lessons" },
    roles: ALL_ROLES,
    steps: [
      {
        key: "loop",
        target: T.lessonsLoop,
        placement: "bottom",
        title: "Решение не заканчивается голосованием",
        body: "После исполнения организация сопоставляет план и факт, объясняет отклонение и формулирует применимый урок.",
        responsibility: "Закрывайте цикл только после фиксации знания для будущих решений.",
      },
      {
        key: "registry",
        target: T.lessonsRegistry,
        placement: "top",
        title: "Plan → Fact → Lesson",
        body: "Каждая запись сохраняет ожидание, фактическое событие, категорию причины и вывод — без ретроспективного переписывания исходного плана.",
        responsibility: "Отделяйте наблюдаемый факт от объяснения причины.",
      },
      {
        key: "similarity",
        target: T.lessonsSimilarity,
        targetPolicy: "optional-rbac",
        placement: "left",
        title: "Опыт становится входом следующего решения",
        body: "Поиск похожих вопросов позволяет использовать прошлые отклонения и меры при подготовке нового паспорта.",
        responsibility: "Проверяйте релевантность урока контексту, а не копируйте вывод автоматически.",
        thesisContext: "Обратная связь превращает отдельные решения в организационное обучение.",
      },
    ],
  }),
  pageTour({
    id: "page-boards",
    version: 1,
    title: "Ролевые контуры органов управления",
    description: "Одна доказательная база через стратегическую, инвестиционную, производственную и риск-оптику.",
    route: "/boards",
    routeRef: { routeId: "boards" },
    roles: ALL_ROLES,
    steps: [
      {
        key: "perspectives",
        target: T.boardsPerspective,
        placement: "bottom",
        title: "Четыре управленческие оптики",
        body: "Стратегическая панель читает сценарии, инвестиционная — капитал и чувствительность, производственная — ограничения и HSE, риск-панель — residual exposure и triggers.",
        responsibility: "Выберите компетенцию, а не отдельную копию данных.",
      },
      {
        key: "shared-evidence",
        target: T.boardsEvidence,
        placement: "top",
        title: "Общая доказательная база",
        body: "Это не четыре независимые базы. Одно решение, показатель и риск сохраняют одинаковое значение во всех представлениях.",
        responsibility: "Различайте общие факты и вопрос, который задаёт конкретный орган.",
        thesisContext: "Ролевое представление связывает ответственность с единым цифровым паспортом.",
      },
    ],
  }),
  pageTour({
    id: "page-roadmap",
    version: 1,
    title: "Трансформационная дорожная карта",
    description: "Стандартизация, интеграция, интеллектуализация и масштабирование через KPI-gates.",
    route: "/roadmap",
    routeRef: { routeId: "roadmap" },
    roles: ALL_ROLES,
    steps: [
      {
        key: "phases",
        target: T.roadmapPhases,
        placement: "bottom",
        title: "Четыре фазы трансформации",
        body: "0–6 месяцев — стандартизация и пилот; 6–18 — интеграция; 18–30 — интеллектуализация; 30+ — масштабирование.",
        responsibility: "Календарь задаёт горизонт, но не открывает переход автоматически.",
      },
      {
        key: "gate",
        target: T.roadmapGate,
        placement: "top",
        title: "KPI-gate между фазами",
        body: "Следующая фаза допускается после подтверждения измеримых KPI предыдущего этапа. Факт, порог и разрыв показываются рядом.",
        responsibility: "Если порог не достигнут, масштабирование преждевременно независимо от даты в плане.",
        thesisContext: "Цифровая трансформация сама управляется как доказательное решение.",
      },
    ],
  }),
  pageTour({
    id: "page-audit",
    version: 1,
    title: "Сквозной Audit Timeline",
    description: "Кто, когда, что и почему изменил в управленческом контуре.",
    route: "/audit",
    routeRef: { routeId: "audit" },
    roles: ALL_ROLES,
    steps: [
      {
        key: "filters",
        target: T.auditFilters,
        placement: "bottom",
        title: "Отберите доказательный след",
        body: "Фильтры связывают событие с человеком, действием, сущностью и решением, не превращая журнал в поток технических кодов.",
        responsibility: "Сузьте историю до вопроса или типа изменения, которое проверяете.",
      },
      {
        key: "timeline",
        target: T.auditTimeline,
        placement: "top",
        title: "Человекочитаемая хронология",
        body: "Timeline объясняет автора, время, предмет изменения и управленческий смысл события.",
        responsibility: "Восстановите последовательность evidence, переходов и вердиктов.",
        thesisContext: "Audit обеспечивает воспроизводимость управленческого решения.",
      },
      {
        key: "technical",
        target: T.auditTechnical,
        targetPolicy: "optional-rbac",
        placement: "left",
        title: "Before → after по запросу",
        body: "Полная техническая запись доступна после раскрытия. Она сохраняет точность, но не подменяет основной человеческий рассказ.",
        responsibility: "Используйте raw detail для расследования, а не ежедневной навигации.",
      },
    ],
  }),
  pageTour({
    id: "page-admin",
    version: 1,
    title: "Администрирование цифрового контура",
    description: "Пользователи, роли, органы и gate policy без подмены business authority.",
    route: "/admin",
    routeRef: { routeId: "admin" },
    roles: ["ADMIN"],
    steps: [
      {
        key: "users",
        target: T.adminUsers,
        placement: "right",
        title: "Пользователи и роли",
        body: "Роль определяет серверные полномочия: подготовку, подтверждение данных, риск-экспертизу, маршрутизацию или человеческий выбор.",
        responsibility: "Меняйте роль только с пониманием её влияния на действия и аудит.",
      },
      {
        key: "bodies",
        target: T.adminBodies,
        placement: "right",
        title: "Органы принятия решений",
        body: "Справочник органов фиксирует корпоративную компетенцию, которая указывается в каждом паспорте.",
        responsibility: "Техническая запись органа не предоставляет администратору право решать за него.",
      },
      {
        key: "gates",
        target: T.adminGates,
        placement: "top",
        title: "Gate policy",
        body: "Правила определяют минимальные evidence requirements для конкретного перехода и уровня A/B/C.",
        responsibility: "Изменение blocking policy влияет на текущие и будущие паспорта и всегда должно оставаться в audit trail.",
        thesisContext: "Администратор управляет конфигурацией, но не принимает бизнес-решение вместо ответственного органа.",
      },
    ],
  }),
  pageTour({
    id: "page-search",
    version: 1,
    title: "Поиск по контуру решений",
    description: "Решения, показатели, модели и поручения в одном управленческом контексте.",
    route: "/search",
    routeRef: { routeId: "search" },
    roles: ALL_ROLES,
    steps: [
      {
        key: "input",
        target: T.searchInput,
        placement: "bottom",
        title: "Ищите управленческий объект",
        body: "Поиск принимает код решения, предмет вопроса, показатель, модель или формулировку поручения.",
        responsibility: "Начните с устойчивого кода, если нужно восстановить точный цифровой след.",
      },
      {
        key: "results",
        target: T.searchResults,
        targetPolicy: "optional-rbac",
        placement: "top",
        title: "Результаты сохраняют контекст",
        body: "Каждый результат показывает не только название, но и стадию, источник, владельца или ответственного исполнителя.",
        responsibility: "Откройте объект, чтобы продолжить в его evidence workspace.",
      },
    ],
  }),
] as const;

/** Exported for content-focused tests without exposing helper internals. */
export const DASHBOARD_PAGE_TOUR_IDS = ROLES.map(
  (role) => `page-dashboard-${role.toLowerCase().replaceAll("_", "-")}`
);

export type PageTourStepDraft = StepDraft;
