import type { Role } from "@/lib/domain";
import { guidedTour } from "@/lib/onboarding/content/helpers";
import { TOUR_TARGETS as T } from "@/lib/onboarding/targets";
import type { TourDefinition } from "@/lib/onboarding/types";

const dashboard = { route: "/dashboard", routeRef: { routeId: "dashboard" } } as const;
const decisions = { route: "/decisions", routeRef: { routeId: "decisions" } } as const;
const passport = {
  route: "/decisions/:id?tab=passport",
  routeRef: { routeId: "decision-passport", query: { tab: "passport" } },
} as const;
const alternatives = {
  route: "/decisions/:id?tab=alternatives",
  routeRef: { routeId: "decision-passport", query: { tab: "alternatives" } },
} as const;
const risks = {
  route: "/decisions/:id?tab=risks",
  routeRef: { routeId: "decision-passport", query: { tab: "risks" } },
} as const;
const economics = {
  route: "/decisions/:id?tab=economics",
  routeRef: { routeId: "decision-passport", query: { tab: "economics" } },
} as const;
const assignments = {
  route: "/decisions/:id?tab=assignments",
  routeRef: { routeId: "decision-passport", query: { tab: "assignments" } },
} as const;
const ai = {
  route: "/decisions/:id?tab=ai",
  routeRef: { routeId: "decision-passport", query: { tab: "ai" } },
} as const;
const decisionAudit = {
  route: "/decisions/:id?tab=audit",
  routeRef: { routeId: "decision-passport", query: { tab: "audit" } },
} as const;

function roleTour(
  role: Role,
  id: string,
  title: string,
  description: string,
  steps: Parameters<typeof guidedTour>[1]["steps"]
): TourDefinition {
  return guidedTour("ROLE", {
    id,
    version: 1,
    title,
    description,
    roles: [role],
    ...dashboard,
    estimatedMinutes: 7,
    steps,
  });
}

export const ROLE_TOURS: readonly TourDefinition[] = [
  roleTour(
    "INITIATOR",
    "role-initiator",
    "Рабочий маршрут инициатора",
    "От управленческого вопроса до доказательной базы, поручений и обратной связи.",
    [
      {
        key: "portfolio",
        ...dashboard,
        target: T.dashboardActionQueue,
        placement: "bottom",
        section: "1. Портфель",
        title: "Начните со своей очереди",
        body: "Очередь показывает паспорта, где именно инициатор должен уточнить вопрос, собрать доказательства или устранить причину возврата.",
        responsibility: "Выберите наиболее критичное действие, а не просто самый новый документ.",
      },
      {
        key: "registry",
        ...decisions,
        target: T.decisionsRegistry,
        placement: "bottom",
        section: "1. Портфель",
        title: "Управляйте вопросами через реестр",
        body: "Код, уровень A/B/C, стадия, орган, срок и gate status позволяют увидеть состояние каждого управленческого вопроса.",
        responsibility: "Сигнал «застряло на стадии» означает нехватку доказательств, которую нужно устранить.",
      },
      {
        key: "create",
        route: "/decisions/new",
        routeRef: { routeId: "decision-new" },
        target: T.decisionNewForm,
        placement: "right",
        section: "2. Доказательная база",
        title: "Сформулируйте решение, а не тему документа",
        body: "Новый паспорт начинается с измеримой цели, типа вопроса, уровня критичности и компетентного органа принятия.",
        responsibility: "Зафиксируйте ожидаемый результат и границы решения до сбора материалов.",
        thesisContext: "DecisionPassport делает единицей управления решение с жизненным циклом, а не файл согласования.",
      },
      {
        key: "criticality",
        route: "/decisions/new",
        routeRef: { routeId: "decision-new" },
        target: T.decisionNewCriticality,
        placement: "left",
        section: "2. Доказательная база",
        title: "Уровень задаёт глубину доказательств",
        body: "A требует расширенных сценариев, допущений, risk profile и независимой проверки; B — стандартного набора; C — упрощённого маршрута.",
        responsibility: "Не занижайте уровень ради более быстрого прохождения ворот.",
      },
      {
        key: "passport",
        ...passport,
        target: T.evidenceIndex,
        placement: "right",
        section: "2. Доказательная база",
        title: "Соберите девять блоков паспорта",
        body: "Идентификация, данные, альтернативы, экономика, безопасность, риски, решение, исполнение и пост-оценка образуют единое проверяемое досье.",
        responsibility: "Следите за полнотой обязательных блоков и назначайте владельцев недостающих доказательств.",
      },
      {
        key: "status-quo",
        ...alternatives,
        target: T.alternativesStatusQuo,
        placement: "right",
        section: "3. Экспертиза",
        title: "Не исключайте статус-кво",
        body: "Вариант «ничего не менять» создаёт базу сравнения. Для существенного решения без него сценарный анализ не считается полным.",
        responsibility: "Опишите последствия бездействия и сравните все варианты по одним критериям.",
      },
      {
        key: "gate",
        ...passport,
        target: T.gateMissingEvidence,
        placement: "left",
        section: "4. Решение",
        title: "Закройте конкретные разрывы gate",
        body: "Ворота не принимают решение: они показывают отсутствующее доказательство и роль, которая обязана его предоставить.",
        responsibility: "Используйте прямую ссылку gate и передайте замечание правильному владельцу.",
      },
      {
        key: "assignment",
        ...assignments,
        target: T.assignmentsKpi,
        placement: "left",
        section: "5. Контроль",
        title: "Свяжите поручение с результатом",
        body: "Поручение получает исполнителя, срок и KPI. Система контролирует не только факт закрытия задачи, но и измеримый эффект.",
        responsibility: "Формулируйте поручение так, чтобы фактический результат можно было проверить.",
      },
      {
        key: "feedback",
        route: "/lessons",
        routeRef: { routeId: "lessons" },
        target: T.lessonsLoop,
        placement: "bottom",
        section: "5. Контроль",
        title: "Завершите цикл пост-оценкой",
        body: "После исполнения сопоставьте план и факт, объясните отклонение и сохраните урок для следующих решений.",
        responsibility: "Решение заканчивается не голосованием, а проверкой достигнутого эффекта.",
      },
    ]
  ),
  roleTour(
    "DATA_OWNER",
    "role-data-owner",
    "Рабочий маршрут владельца данных",
    "Подтверждение качества, актуальности и происхождения критических показателей.",
    [
      {
        key: "queue",
        ...dashboard,
        target: T.dashboardActionQueue,
        placement: "bottom",
        section: "1. Портфель",
        title: "Найдите ожидающие подтверждения",
        body: "Персональная очередь содержит показатели, где ваша проверка источника, актуальности и качества удерживает decision gate закрытым.",
        responsibility: "Вы отвечаете за данные в своей зоне, но не за окончательный выбор альтернативы.",
      },
      {
        key: "catalog",
        route: "/indicators",
        routeRef: { routeId: "indicators" },
        target: T.indicatorCatalog,
        placement: "bottom",
        section: "2. Доказательная база",
        title: "Работайте с единым определением показателя",
        body: "Каталог связывает бизнес-смысл, формулу, систему-источник, владельца, критичность и качество показателя.",
        responsibility: "Проверьте, что одно название не используется для разных методик расчёта.",
      },
      {
        key: "definition",
        route: "/indicators/:id",
        routeRef: { routeId: "indicator-detail" },
        target: T.indicatorDefinition,
        placement: "right",
        section: "2. Доказательная база",
        title: "Подтвердите смысл и формулу",
        body: "Число становится доказательством только вместе с определением единицы измерения, формулы и допустимого применения.",
        responsibility: "Исправьте двусмысленное определение до подтверждения значения.",
      },
      {
        key: "freshness",
        route: "/indicators/:id",
        routeRef: { routeId: "indicator-detail" },
        target: T.indicatorFreshness,
        placement: "left",
        section: "3. Экспертиза",
        title: "Проверьте дату актуальности",
        body: "Корректное в прошлом значение может стать непригодным для текущего решения. Freshness показывает возраст и статус обновления.",
        responsibility: "Не подтверждайте устаревшее значение без явного ограничения.",
      },
      {
        key: "nature",
        route: "/indicators/:id",
        routeRef: { routeId: "indicator-detail" },
        target: T.indicatorNature,
        placement: "right",
        section: "3. Экспертиза",
        title: "Разделяйте факт, прогноз и допущение",
        body: "Факт измерен, прогноз рассчитан моделью, а допущение является проверяемым управленческим предположением о будущем.",
        responsibility: "Маркируйте природу значения: смешение создаёт ложную уверенность в доказательной базе.",
        thesisContext: "Разделение типов знания — условие воспроизводимости управленческого вывода.",
      },
      {
        key: "lineage",
        route: "/indicators/:id",
        routeRef: { routeId: "indicator-detail" },
        target: T.indicatorLineage,
        placement: "top",
        section: "3. Экспертиза",
        title: "Восстановите data lineage",
        body: "Цепочка проходит от системы-источника через интеграцию и контроль качества к каталогу, значению, решению и бизнес-выводу.",
        responsibility: "Убедитесь, что любое критическое число можно воспроизвести и проверить.",
      },
      {
        key: "gate-impact",
        ...passport,
        target: T.decisionGate,
        placement: "left",
        section: "4. Решение",
        title: "Ваше подтверждение влияет на gate",
        body: "Для критических данных отсутствие источника, владельца или подтверждения качества блокирует переход паспорта на следующую стадию.",
        responsibility: "Подтверждайте только проверенную часть; решение о выборе остаётся за уполномоченным органом.",
      },
      {
        key: "trace",
        ...decisionAudit,
        target: T.decisionAuditTimeline,
        placement: "left",
        section: "5. Контроль",
        title: "Сохраните воспроизводимый след",
        body: "Аудит фиксирует, кто, когда и на каком основании подтвердил значение или изменил его статус.",
        responsibility: "Используйте комментарий подтверждения для существенных ограничений данных.",
      },
    ]
  ),
  roleTour(
    "RISK_OFFICER",
    "role-risk-officer",
    "Рабочий маршрут риск-офицера",
    "От исходной оценки до остаточного риска, владельца, триггера и gate.",
    [
      {
        key: "queue",
        ...dashboard,
        target: T.dashboardActionQueue,
        placement: "bottom",
        section: "1. Портфель",
        title: "Найдите неполный risk profile",
        body: "Очередь выделяет решения без оценки вероятности, воздействия, мер, остаточного риска, владельца или триггера пересмотра.",
        responsibility: "Приоритизируйте уровень A и риски, способные изменить допустимость решения.",
      },
      {
        key: "initial",
        ...risks,
        target: T.riskInitial,
        placement: "right",
        section: "2. Доказательная база",
        title: "Зафиксируйте исходный риск",
        body: "Initial risk отражает вероятность и воздействие до мер реагирования — исходную экспозицию организации.",
        responsibility: "Оцените оба параметра на единой шкале и укажите основание оценки.",
      },
      {
        key: "mitigation",
        ...risks,
        target: T.riskMitigation,
        placement: "right",
        section: "3. Экспертиза",
        title: "Свяжите риск с реальной мерой",
        body: "Mitigation должна снижать вероятность или воздействие, иметь конкретное действие и проверяемый результат.",
        responsibility: "Не используйте общие формулировки вроде «усилить контроль» без механизма и срока.",
      },
      {
        key: "residual",
        ...risks,
        target: T.riskResidual,
        placement: "left",
        section: "3. Экспертиза",
        title: "Покажите остаточный риск",
        body: "Residual risk — экспозиция, которая остаётся после мер. Именно её организация осознанно принимает вместе с выбранной альтернативой.",
        responsibility: "Пересчитайте остаточную оценку после изменения меры, а не копируйте исходную.",
        thesisContext: "Решение оценивается по риску после контроля, а не только по первоначальной угрозе.",
      },
      {
        key: "owner-trigger",
        ...risks,
        target: T.riskOwnerTrigger,
        placement: "top",
        section: "3. Экспертиза",
        title: "Назначьте владельца и триггер",
        body: "Владелец наблюдает за риском, а trigger определяет событие или порог, при котором оценка и решение должны быть пересмотрены.",
        responsibility: "Укажите роль, срок мониторинга и измеримый сигнал эскалации.",
      },
      {
        key: "gate",
        ...passport,
        target: T.gateMissingEvidence,
        placement: "left",
        section: "4. Решение",
        title: "Risk profile является gate evidence",
        body: "Для уровней A и B неполный риск-профиль блокирует переход. Для A дополнительно проверяются допущения и независимая экспертиза.",
        responsibility: "Закройте только собственные требования; решение принимает компетентный орган.",
      },
      {
        key: "audit",
        route: "/audit",
        routeRef: { routeId: "audit" },
        target: T.auditTimeline,
        placement: "left",
        section: "5. Контроль",
        title: "Отслеживайте изменение риск-профиля",
        body: "Сквозной audit trail показывает историю оценки, мер, владельцев и решения о принятии остаточного риска.",
        responsibility: "При срабатывании триггера инициируйте пересмотр и сохраните основание.",
      },
    ]
  ),
  roleTour(
    "ANALYST",
    "role-analyst",
    "Рабочий маршрут аналитика",
    "Сопоставимые альтернативы, проверяемые расчёты, модели и baseline → pilot.",
    [
      {
        key: "queue",
        ...dashboard,
        target: T.dashboardActionQueue,
        placement: "bottom",
        section: "1. Портфель",
        title: "Найдите аналитический разрыв",
        body: "Очередь ведёт к неполным сценариям, альтернативам, расчётам и материалам, которым нужна независимая проверка.",
        responsibility: "Начните с доказательства, которое удерживает наиболее критичный gate.",
      },
      {
        key: "indicators",
        route: "/indicators",
        routeRef: { routeId: "indicators" },
        target: T.indicatorCatalog,
        placement: "bottom",
        section: "2. Доказательная база",
        title: "Используйте определённые показатели",
        body: "Формула, источник, владелец и freshness делают исходные данные расчёта проверяемыми.",
        responsibility: "Не подменяйте подтверждённый факт прогнозом или неявным допущением.",
      },
      {
        key: "matrix",
        ...alternatives,
        target: T.alternativesMatrix,
        placement: "top",
        section: "2. Доказательная база",
        title: "Сравнивайте варианты симметрично",
        body: "Статус-кво и содержательные альтернативы оцениваются по единому набору критериев: безопасность, регуляторика, экономика, срок, ресурсы, персонал, cyber и устойчивость.",
        responsibility: "Не меняйте критерий только потому, что он ухудшает предпочитаемый вариант.",
      },
      {
        key: "assumptions",
        ...risks,
        target: T.assumptionsRegister,
        placement: "right",
        section: "3. Экспертиза",
        title: "Сделайте допущения проверяемыми",
        body: "Допущение описывает будущее условие и имеет срок действия. После исполнения его нужно сопоставить с фактом.",
        responsibility: "Зафиксируйте источник, чувствительность результата и дату пересмотра.",
      },
      {
        key: "economics",
        ...economics,
        target: T.economicsMissing,
        placement: "left",
        section: "3. Экспертиза",
        title: "Не достраивайте отсутствующие деньги",
        body: "Трудоёмкость, risk effect, NPV и attributionShare появляются только после ввода необходимых параметров; система не показывает выдуманный эффект.",
        responsibility: "Отметьте missing parameters и владельца ввода вместо оценки «на глаз».",
      },
      {
        key: "models",
        route: "/models",
        routeRef: { routeId: "models" },
        target: T.modelGovernance,
        placement: "left",
        section: "3. Экспертиза",
        title: "Проверьте применимость модели",
        body: "Версия, владелец, дата валидации, ограничения и разрешённые уровни критичности задают границы аналитического вывода.",
        responsibility: "Не переносите рекомендацию за пределы валидированного сценария.",
      },
      {
        key: "ai",
        ...ai,
        target: T.aiSources,
        placement: "right",
        section: "4. Решение",
        title: "Свяжите рекомендацию с источниками",
        body: "AI workspace обязан показывать использованные факты, ключевые факторы, неопределённости и ограничения модели.",
        responsibility: "Проверьте воспроизводимость вывода; рекомендация остаётся аналитическим входом.",
      },
      {
        key: "verification",
        ...ai,
        target: T.aiHumanVerdict,
        placement: "left",
        section: "4. Решение",
        title: "Сохраните независимость человеческого вердикта",
        body: "Принять, принять с изменениями и отклонить — равноправные действия. Для уровня A мотивировка обязательна.",
        responsibility: "Аналитик обосновывает расчёт, но не присваивает полномочие органа управления.",
      },
      {
        key: "baseline",
        route: "/kpi",
        routeRef: { routeId: "kpi" },
        target: T.kpiComparison,
        placement: "top",
        section: "5. Контроль",
        title: "Проверьте эффект по baseline → pilot",
        body: "Одинаковые метрика, период и выборка позволяют сопоставить исходное и пилотное значение и рассчитать delta.",
        responsibility: "Не объявляйте эффект, если база сравнения методологически несовместима.",
      },
    ]
  ),
  roleTour(
    "SECRETARY",
    "role-secretary",
    "Рабочий маршрут корпоративного секретаря",
    "Компетенция органа, полнота ворот, переходы, возвраты и audit trail.",
    [
      {
        key: "queue",
        ...dashboard,
        target: T.dashboardActionQueue,
        placement: "bottom",
        section: "1. Портфель",
        title: "Контролируйте корпоративный маршрут",
        body: "Очередь показывает вопросы, где нужно проверить орган, комплектность gate evidence, переход стадии или основание возврата.",
        responsibility: "Вы обеспечиваете корректность процесса, но не голосуете вместо органа.",
      },
      {
        key: "registry",
        ...decisions,
        target: T.decisionsFilters,
        placement: "bottom",
        section: "1. Портфель",
        title: "Найдите вопросы по органу и стадии",
        body: "Фильтры реестра отделяют готовые к рассмотрению вопросы от возвращённых и застрявших на контрольных воротах.",
        responsibility: "Проверяйте срок, ответственного и компетенцию органа до включения в повестку.",
      },
      {
        key: "header",
        ...passport,
        target: T.decisionHeader,
        placement: "bottom",
        section: "2. Доказательная база",
        title: "Проверьте контрольные реквизиты",
        body: "Код, тип, критичность, инициатор, орган и deadline определяют применимый маршрут и требуемую глубину экспертизы.",
        responsibility: "Несоответствие компетенции должно быть устранено до содержательного рассмотрения.",
      },
      {
        key: "stage",
        ...passport,
        target: T.decisionStageRail,
        placement: "top",
        section: "2. Доказательная база",
        title: "Семь стадий образуют управляемый процесс",
        body: "Проблема, данные, альтернативы, риски, решение, исполнение и обратная связь не позволяют потерять контекст после голосования.",
        responsibility: "Открывайте переход только из фактической текущей стадии.",
      },
      {
        key: "gate",
        ...passport,
        target: T.decisionGate,
        placement: "left",
        section: "3. Экспертиза",
        title: "Gate проверяет достаточность",
        body: "Контрольные ворота применяют правила соответствующего уровня A/B/C и не подменяют содержательный вердикт органа.",
        responsibility: "Сверьте каждое правило и владельца отсутствующего доказательства.",
      },
      {
        key: "return",
        ...passport,
        target: T.gateMissingEvidence,
        placement: "left",
        section: "4. Решение",
        title: "Возврат должен быть адресным",
        body: "Система показывает конкретное невыполненное правило, объяснение и ответственную роль вместо общего статуса «не согласовано».",
        responsibility: "Зафиксируйте проверяемое основание возврата и прямую ссылку на блок.",
      },
      {
        key: "boards",
        route: "/boards",
        routeRef: { routeId: "boards" },
        target: T.boardsEvidence,
        placement: "top",
        section: "4. Решение",
        title: "Подготовьте перспективу органа",
        body: "Рабочий контур органа собирает вопросы и доказательства в соответствии с его компетенцией.",
        responsibility: "Убедитесь, что пакет содержит версии материалов, рассмотренные органом.",
      },
      {
        key: "audit",
        ...decisionAudit,
        target: T.decisionAuditTimeline,
        placement: "left",
        section: "5. Контроль",
        title: "Сохраните историю переходов и решений",
        body: "Audit trail связывает действие, автора, время, основание и объект изменения в воспроизводимый корпоративный след.",
        responsibility: "Не заменяйте структурированное событие внешней перепиской без привязки к паспорту.",
      },
    ]
  ),
  roleTour(
    "BOARD_MEMBER",
    "role-board-member",
    "Рабочий маршрут члена органа управления",
    "От критического вопроса и доказательств до мотивированного человеческого вердикта.",
    [
      {
        key: "queue",
        ...dashboard,
        target: T.dashboardActionQueue,
        placement: "bottom",
        section: "1. Портфель",
        title: "Найдите вопросы для человеческого решения",
        body: "Очередь отделяет готовые к рассмотрению паспорта от тех, где доказательная база ещё не прошла обязательные ворота.",
        responsibility: "Не воспринимайте техническую готовность как автоматическое одобрение содержания.",
      },
      {
        key: "criticality",
        ...decisions,
        target: T.decisionCriticality,
        targetPolicy: "optional-rbac",
        placement: "right",
        section: "1. Портфель",
        title: "Уровень A требует усиленной осмотрительности",
        body: "Для наиболее существенных решений обязательны сценарии, допущения, риск-профиль, независимая проверка и запрет автоматического вердикта.",
        responsibility: "Проверьте, что глубина evidence соответствует последствиям выбора.",
      },
      {
        key: "readiness",
        ...passport,
        target: T.decisionReadiness,
        placement: "left",
        section: "2. Доказательная база",
        title: "Readiness — это полнота доказательств",
        body: "Процент показывает заполненность обязательного досье, а не процент выполнения проекта и не вероятность успеха.",
        responsibility: "Откройте индекс evidence и изучите незакрытые блоки.",
      },
      {
        key: "alternatives",
        ...alternatives,
        target: T.alternativesHumanDecision,
        placement: "left",
        section: "3. Экспертиза",
        title: "Сопоставьте варианты и статус-кво",
        body: "Единые критерии делают компромиссы видимыми, но итоговый score не заменяет управленческое суждение органа.",
        responsibility: "Объясните, почему выбранный вариант предпочтительнее бездействия и иных альтернатив.",
      },
      {
        key: "risk",
        ...risks,
        target: T.riskResidual,
        placement: "left",
        section: "3. Экспертиза",
        title: "Принимайте решение вместе с остаточным риском",
        body: "Residual risk показывает, какая экспозиция остаётся после мер и фактически принимается организацией.",
        responsibility: "Проверьте владельца, trigger и допустимость остаточного профиля.",
      },
      {
        key: "ai-governance",
        ...ai,
        target: T.aiGovernance,
        placement: "right",
        section: "3. Экспертиза",
        title: "Проверьте границы модели",
        body: "Версия, владелец, дата валидации, допустимые уровни критичности и ограничения определяют, где рекомендация применима.",
        responsibility: "Не используйте модель за пределами её разрешённого класса решений.",
      },
      {
        key: "not-applied",
        ...ai,
        target: T.aiNotApplied,
        placement: "top",
        section: "4. Решение",
        title: "Рекомендация не применена автоматически",
        body: "ИИ предоставляет аналитическую поддержку, но не обладает полномочиями принять юридически и управленчески значимое решение.",
        responsibility: "Сначала проверьте источники, ключевые факторы, неопределённости и ограничения.",
        thesisContext: "Human-in-the-loop сохраняет полномочия и ответственность за человеком и компетентным органом.",
      },
      {
        key: "verdict",
        ...ai,
        target: T.aiHumanVerdict,
        placement: "left",
        section: "4. Решение",
        title: "Зафиксируйте собственный мотивированный вердикт",
        body: "«Принять», «принять с изменениями» и «отклонить» равноправны. Для уровня A обязательна мотивировка человека.",
        responsibility: "Свяжите выбор с рассмотренными доказательствами и принятым риском.",
      },
      {
        key: "trace",
        ...decisionAudit,
        target: T.decisionAuditTimeline,
        placement: "left",
        section: "5. Контроль",
        title: "Вердикт остаётся в цифровом следе",
        body: "Паспорт сохраняет рассмотренную версию evidence, человеческое решение и последующую оценку фактического результата.",
        responsibility: "Используйте audit trail для восстановления основания, а не для формальной отметки согласования.",
      },
    ]
  ),
  roleTour(
    "ADMIN",
    "role-admin",
    "Рабочий маршрут администратора",
    "Пользователи, роли, органы, gate policy, модели и воспроизводимый аудит.",
    [
      {
        key: "boundary",
        ...dashboard,
        target: T.dashboardActionQueue,
        placement: "bottom",
        section: "1. Портфель",
        title: "Поддерживайте контур, не подменяя роли",
        body: "Администратор устраняет конфигурационные разрывы и обеспечивает доступность правил, но не принимает бизнес-решения.",
        responsibility: "Разделяйте техническое полномочие и ответственность владельца процесса.",
      },
      {
        key: "users",
        route: "/admin",
        routeRef: { routeId: "admin" },
        target: T.adminUsers,
        placement: "right",
        section: "2. Конфигурация",
        title: "Управляйте пользователями и ролями",
        body: "Роль определяет видимую очередь, доступные действия и ответственность в gate, а не только подпись в интерфейсе.",
        responsibility: "Выдавайте минимально необходимые полномочия и проверяйте конфликт ролей.",
      },
      {
        key: "bodies",
        route: "/admin",
        routeRef: { routeId: "admin" },
        target: T.adminBodies,
        placement: "right",
        section: "2. Конфигурация",
        title: "Поддерживайте справочник органов",
        body: "Орган принятия связывает паспорт с компетенцией и корпоративным маршрутом рассмотрения.",
        responsibility: "Не удаляйте исторически использованный орган без сохранения ссылочной целостности.",
      },
      {
        key: "gates",
        route: "/admin",
        routeRef: { routeId: "admin" },
        target: T.adminGates,
        placement: "left",
        section: "3. Правила",
        title: "Gate policy задаёт требования, а не решение",
        body: "Настройка связывает стадию, критичность и обязательное доказательство. Она не должна давать алгоритму право вынести вердикт.",
        responsibility: "Изменяйте правила контролируемо и сохраняйте основание версии.",
      },
      {
        key: "models",
        route: "/models",
        routeRef: { routeId: "models" },
        target: T.modelGovernance,
        placement: "left",
        section: "3. Правила",
        title: "Поддерживайте model governance",
        body: "Для каждой модели нужны версия, владелец, дата валидации, ограничения и разрешённые уровни A/B/C.",
        responsibility: "Закрывайте применение просроченной или недопустимой версии без изменения исторического следа.",
      },
      {
        key: "roadmap",
        route: "/roadmap",
        routeRef: { routeId: "roadmap" },
        target: T.roadmapGate,
        placement: "left",
        section: "4. Развитие",
        title: "Развивайте платформу через проверяемые gates",
        body: "Дорожная карта связывает технологический этап с измеримым критерием готовности, а не только с календарной датой.",
        responsibility: "Не открывайте следующий этап без доказательства достижения текущего.",
      },
      {
        key: "audit",
        route: "/audit",
        routeRef: { routeId: "audit" },
        target: T.auditTechnical,
        placement: "left",
        section: "5. Контроль",
        title: "Технические события не равны бизнес-решениям",
        body: "Аудит различает входы и системные операции, изменения evidence, переходы gate и человеческие вердикты.",
        responsibility: "Поддерживайте целостность следа и расследуйте аномалии без редактирования истории.",
      },
    ]
  ),
] as const;

