import { guidedTour } from "@/lib/onboarding/content/helpers";
import { TOUR_TARGETS as T } from "@/lib/onboarding/targets";
import type { TourDefinition } from "@/lib/onboarding/types";

const dashboard = { route: "/dashboard", routeRef: { routeId: "dashboard" } } as const;
const passport = {
  route: "/decisions/:id?tab=passport",
  routeRef: { routeId: "decision-passport", query: { tab: "passport" } },
} as const;
const alternatives = {
  route: "/decisions/:id?tab=alternatives",
  routeRef: { routeId: "decision-passport", query: { tab: "alternatives" } },
} as const;
const risks = {
  route: "/decisions/:id?tab=risks",
  routeRef: { routeId: "decision-passport", query: { tab: "risks" } },
} as const;
const economics = {
  route: "/decisions/:id?tab=economics",
  routeRef: { routeId: "decision-passport", query: { tab: "economics" } },
} as const;
const assignments = {
  route: "/decisions/:id?tab=assignments",
  routeRef: { routeId: "decision-passport", query: { tab: "assignments" } },
} as const;
const ai = {
  route: "/decisions/:id?tab=ai",
  routeRef: { routeId: "decision-passport", query: { tab: "ai" } },
} as const;

/**
 * Self-guided dissertation demonstration. Cross-page routes intentionally use
 * App Router patterns for entity pages: the UI resolves them to the currently
 * selected demo decision/indicator before navigation.
 */
export const THESIS_TOURS: readonly TourDefinition[] = [
  guidedTour("THESIS", {
    id: "thesis-jury-methodology",
    version: 1,
    title: "DecisionPassport: полный цикл управленческого решения",
    description: "Самостоятельная 10–15-минутная экскурсия по научной модели, доказательствам, полномочиям и обратной связи.",
    route: "/login",
    routeRef: { routeId: "login" },
    estimatedMinutes: 13,
    steps: [
      {
        key: "purpose",
        route: "/login",
        routeRef: { routeId: "login" },
        target: T.body,
        placement: "center",
        section: "1. Научная идея",
        title: "Зачем создан DecisionPassport",
        body: "Платформа связывает постановку вопроса, данные, аналитику, альтернативы, риски, полномочия органа, исполнение и измерение результата в одном цифровом контуре.",
        thesisContext: "Главный объект системы — управленческое решение на всём жизненном цикле, а не документ как конечный результат согласования.",
      },
      {
        key: "choose-role",
        route: "/login",
        routeRef: { routeId: "login" },
        target: T.loginRoleGroups,
        targetPolicy: "optional-rbac",
        placement: "right",
        advance: "target-click",
        section: "1. Научная идея",
        title: "Посмотрите на одну базу через выбранную роль",
        body: "Выберите демонстрационную роль. После входа экскурсия продолжится на dashboard, а объяснения сохранят границы полномочий выбранного участника.",
        responsibility: "Для защиты удобно начать с инициатора или члена органа управления; методология одинакова для всех ролей.",
      },
      {
        key: "portfolio",
        ...dashboard,
        target: T.dashboardOverview,
        placement: "bottom",
        section: "1. Научная идея",
        title: "Портфель показывает состояние решений",
        body: "Dashboard отвечает не на вопрос «сколько файлов создано», а где находятся существенные вопросы и какой части доказательной базы им не хватает.",
        responsibility: "Выберите решение уровня A как сквозной демонстрационный пример.",
      },
      {
        key: "criticality",
        ...dashboard,
        target: T.dashboardCriticality,
        placement: "left",
        section: "1. Научная идея",
        title: "A, B и C задают пропорциональность контроля",
        body: "Уровень A применяется к наиболее существенным решениям и требует расширенных сценариев, допущений, risk profile и независимой проверки. B использует стандартный набор, C — упрощённый.",
        thesisContext: "Глубина доказательств растёт вместе с последствиями решения; автоматический вердикт для уровня A запрещён.",
      },
      {
        key: "lifecycle",
        ...dashboard,
        target: T.dashboardProcessRail,
        placement: "top",
        section: "2. Жизненный цикл",
        title: "Семь стадий сохраняют причинную цепочку",
        body: "Проблема → Данные → Альтернативы → Риски → Решение → Исполнение → Обратная связь. Процесс не заканчивается рассмотрением вопроса органом.",
        thesisContext: "Стадии связывают исходную гипотезу решения с фактически достигнутым результатом.",
      },
      {
        key: "gates",
        ...dashboard,
        target: T.dashboardGates,
        placement: "left",
        section: "2. Жизненный цикл",
        title: "Decision gates проверяют достаточность",
        body: "Ворота не выбирают альтернативу. Они проверяют обязательные доказательства текущего уровня и объясняют, почему переход заблокирован.",
        responsibility: "Закрытый gate — управленческий сигнал о конкретном разрыве, а не ошибка интерфейса.",
      },
      {
        key: "passport",
        ...passport,
        target: T.decisionHeader,
        placement: "bottom",
        section: "3. Цифровой паспорт",
        title: "Паспорт объединяет контекст решения",
        body: "Код, цель, тип, критичность, орган, инициатор и срок идентифицируют один управленческий вопрос и применимый к нему маршрут.",
        thesisContext: "Цифровой паспорт — единая доказательная база, а не папка несвязанных приложений.",
      },
      {
        key: "readiness",
        ...passport,
        target: T.decisionReadiness,
        placement: "left",
        section: "3. Цифровой паспорт",
        title: "Readiness измеряет полноту evidence",
        body: "Процент готовности не является процентом выполнения проекта или прогнозом успеха. Он отражает заполненность обязательных доказательств.",
        responsibility: "Низкая готовность ведёт к конкретным незаполненным блокам.",
      },
      {
        key: "evidence-index",
        ...passport,
        target: T.evidenceIndex,
        placement: "right",
        section: "3. Цифровой паспорт",
        title: "Девять блоков формируют досье",
        body: "01 Идентификация, 02 Данные, 03 Альтернативы, 04 Экономика, 05 Безопасность, 06 Риски, 07 Решение, 08 Исполнение и 09 Пост-оценка.",
        thesisContext: "Структура сохраняет связь между основанием выбора, ответственностью и результатом.",
      },
      {
        key: "gate-explanation",
        ...passport,
        target: T.gateMissingEvidence,
        placement: "left",
        section: "3. Цифровой паспорт",
        title: "Блокировка объяснима и адресна",
        body: "Для каждого невыполненного правила система показывает отсутствующее доказательство, объяснение и роль, которая обязана его предоставить.",
        responsibility: "Прямая ссылка ведёт не на общую страницу, а к месту устранения разрыва.",
      },
      {
        key: "data-lineage",
        route: "/indicators/:id",
        routeRef: { routeId: "indicator-detail" },
        target: T.indicatorLineage,
        placement: "top",
        section: "4. Качество знания",
        title: "Data lineage делает число воспроизводимым",
        body: "Source system → интеграция и контроль качества → каталог → значение → решение → бизнес-вывод. Цепочка восстанавливает происхождение использованного показателя.",
        thesisContext: "Число без источника, владельца и даты актуальности не считается полноценным доказательством существенного решения.",
      },
      {
        key: "epistemic-types",
        route: "/indicators/:id",
        routeRef: { routeId: "indicator-detail" },
        target: T.indicatorNature,
        placement: "right",
        section: "4. Качество знания",
        title: "Факт, прогноз и допущение нельзя смешивать",
        body: "Факт — подтверждённое измерение; прогноз — результат аналитической модели; допущение — явно зафиксированное предположение о будущем, которое позднее проверяется.",
        thesisContext: "Разная природа значений требует разной степени доверия и способа проверки.",
      },
      {
        key: "alternatives",
        ...alternatives,
        target: T.alternativesMatrix,
        placement: "top",
        section: "5. Сценарный выбор",
        title: "Альтернативы сравниваются по одним критериям",
        body: "Безопасность, регуляторика, экономика, срок, ресурсы, персонал, cyber risk и устойчивость применяются симметрично ко всем вариантам.",
        responsibility: "Несколько названий ещё не образуют качественный сценарный анализ.",
      },
      {
        key: "status-quo",
        ...alternatives,
        target: T.alternativesStatusQuo,
        placement: "right",
        section: "5. Сценарный выбор",
        title: "Статус-кво — обязательная база сравнения",
        body: "Вариант «ничего не менять» показывает цену бездействия. Без него нельзя доказать, что изменение лучше сохранения текущего состояния.",
        thesisContext: "Для существенного решения полнота сценарного анализа проверяется gate rule.",
      },
      {
        key: "residual-risk",
        ...risks,
        target: T.riskResidual,
        placement: "left",
        section: "5. Сценарный выбор",
        title: "Орган принимает остаточный риск",
        body: "Initial risk оценивается до мер, mitigation снижает экспозицию, residual risk показывает то, что останется после контроля.",
        responsibility: "Владелец и trigger определяют, кто наблюдает риск и когда решение пересматривается.",
      },
      {
        key: "economics",
        ...economics,
        target: T.economicsMissing,
        placement: "left",
        section: "6. Проверяемая аналитика",
        title: "Отсутствующее значение не заменяется выдумкой",
        body: "Трудоёмкость, risk effect, NPV и доля атрибуции рассчитываются только после появления необходимых входов. Missing parameters остаются видимыми.",
        thesisContext: "DecisionPassport не показывает денежный эффект без воспроизводимого расчёта.",
      },
      {
        key: "ai-governance",
        ...ai,
        target: T.aiGovernance,
        placement: "right",
        section: "6. Проверяемая аналитика",
        title: "AI workspace начинается с governance",
        body: "Модель, версия, владелец, дата валидации, допустимые уровни критичности и ограничения задают область применимости рекомендации.",
        responsibility: "Затем проверяются источники, обоснование, ключевые факторы и неопределённости.",
      },
      {
        key: "human-loop",
        ...ai,
        target: T.aiNotApplied,
        placement: "top",
        section: "7. Полномочия",
        title: "ИИ не принимает решение",
        body: "Рекомендация не применяется автоматически. Человек может принять её, принять с изменениями или отклонить и обязан мотивировать вердикт уровня A.",
        thesisContext: "Human-in-the-loop сохраняет юридические и управленческие полномочия за человеком и соответствующим органом.",
      },
      {
        key: "assignments",
        ...assignments,
        target: T.assignmentsFlow,
        placement: "top",
        section: "8. Исполнение и эффект",
        title: "Решение продолжается в поручениях",
        body: "Decision → Assignment → KPI → Actual result связывает человеческий вердикт с исполнителем, сроком и измеримым результатом.",
        responsibility: "Закрытая задача без достигнутого KPI не доказывает эффект решения.",
      },
      {
        key: "baseline-pilot",
        route: "/kpi",
        routeRef: { routeId: "kpi" },
        target: T.kpiComparison,
        placement: "top",
        section: "8. Исполнение и эффект",
        title: "Эффект измеряется baseline → pilot",
        body: "Одинаковые метрика, выборка и период делают исходное и пилотное значения сопоставимыми; delta показывает наблюдаемое изменение.",
        thesisContext: "До/после без сопоставимой базы не позволяет приписать результат решению.",
      },
      {
        key: "post-evaluation",
        ...assignments,
        target: T.assignmentsActual,
        placement: "left",
        section: "8. Исполнение и эффект",
        title: "Пост-оценка закрывает петлю",
        body: "Plan → Actual → Deviation → Cause → Lesson проверяет ожидаемый эффект после исполнения и объясняет отклонение.",
        responsibility: "Зафиксируйте не только результат, но и причину, чтобы вывод можно было использовать повторно.",
      },
      {
        key: "lessons",
        route: "/lessons",
        routeRef: { routeId: "lessons" },
        target: T.lessonsSimilarity,
        placement: "left",
        section: "9. Организационное обучение",
        title: "Уроки формируют корпоративную память",
        body: "План, факт, причина и вывод связываются с похожими решениями и возвращаются в подготовку новых вопросов.",
        thesisContext: "Обратная связь превращает единичное решение в организационное знание.",
      },
      {
        key: "maturity",
        route: "/kpi",
        routeRef: { routeId: "kpi" },
        target: T.maturityScale,
        placement: "left",
        section: "9. Организационное обучение",
        title: "Зрелость подтверждается измеримыми практиками",
        body: "Шкала зрелости отражает переход от фрагментарных действий к воспроизводимому, измеряемому и обучающемуся контуру решений.",
        responsibility: "Уровень не повышается декларативно: нужны наблюдаемые evidence и результаты.",
      },
      {
        key: "roadmap",
        route: "/roadmap",
        routeRef: { routeId: "roadmap" },
        target: T.roadmapGate,
        placement: "left",
        section: "9. Организационное обучение",
        title: "Roadmap также проходит контрольные ворота",
        body: "Каждая фаза трансформации имеет критерий готовности, поэтому развитие платформы подчиняется той же логике проверяемого перехода.",
        thesisContext: "Метод применяется не только к бизнес-вопросам, но и к внедрению самого управленческого контура.",
      },
      {
        key: "audit",
        route: "/audit",
        routeRef: { routeId: "audit" },
        target: T.auditTimeline,
        placement: "left",
        section: "10. Цифровой след",
        title: "Audit связывает доказательство, действие и полномочие",
        body: "Сквозная хронология сохраняет, кто, когда, в какой роли и на каком основании изменил evidence, прошёл gate или вынес вердикт.",
        thesisContext: "Воспроизводимость решения обеспечивается структурированным следом, а не только финальным протоколом.",
      },
      {
        key: "complete",
        ...dashboard,
        target: T.body,
        placement: "center",
        section: "10. Цифровой след",
        title: "Вы прошли полный цикл DecisionPassport",
        body: "Платформа соединяет данные, аналитику, альтернативы, риски, полномочия органов, исполнение и обратную связь. ИИ поддерживает анализ, но окончательная ответственность сохраняется за человеком.",
        responsibility: "Теперь можно открыть платформу самостоятельно, повторить экскурсию или выбрать другую роль.",
      },
    ],
  }),
] as const;
